### ISSUE TITLE
Key not found Error

### ISSUE THREAD

**Issue by riverallzero** [jbnu-orb/orb#43]
Setup Devleopment Environment 도중 ```flask db migrate```시 아래와 같이 Key 설정 에러가 발생합니다.
.env 파일은 따로 안올려두신걸까요?

```
Key AI_MODEL_BASE_URL not found in .env.
Key SQLALCHEMY_DATABASE_URI not found in .env.
Traceback (most recent call last):
  File "/Users/loa/Desktop/Code/orb/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/cli.py", line 611, in get_command
    app = info.load_app()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/cli.py", line 339, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/loa/Desktop/Code/orb/backend/app.py", line 13, in <module>
    db.init_app(app)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask_sqlalchemy/extension.py", line 355, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.
```

**Comment by zzzz465** [comment]
docker-compose 실행 후 .env 파일 만들어서 아래 값 추가해주세요
```env
SQLALCHEMY_DATABASE_URI=postgresql://devuser:devpassword@localhost:5433/orb
```

템플릿 파일도 올리겠습니다
