### ISSUE TITLE
Register: SignUp Internal Server Error

### ISSUE THREAD

**Issue by riverallzero** [jbnu-orb/orb#65]
backend 테스트 중 아래와 같이 회원가입 시 에러가 나는데 어떻게 해결해야할까요?

![](https://github.com/jbnu-orb/orb/assets/93754504/f93266cf-0e67-4216-96bf-a050dea9df67)
![](https://github.com/jbnu-orb/orb/assets/93754504/8845f1f0-dac9-48ac-9920-a9c54436a211)

+ 아무 정보나 입력해서 로그인 한 경우에도 500 internal server error가 발생하네요..

![](https://github.com/jbnu-orb/orb/assets/93754504/8845f1f0-dac9-48ac-9920-a9c54436a211)

**Comment by kimmason** [comment]
음 제가 동일한 username과 email 사용한 뒤 password는 임의로 숫자 6개 넣어서 회원가입 해봤는데 정상적으로 작동했습니다.
혹시 에러 코드 상세하게 알려주실 수 있나요? 아니면 새 환경구성해서 다시 실행해보시는게..

**Comment by riverallzero** [comment]
환경 구성 새롭게 해서 실행해봐도 저는 저렇게 뜨네요...

```
[2024-06-16 16:52:31,267] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "user" does not exist
LINE 1: INSERT INTO "user" (username, email, password_hash) VALUES (...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/loa/Desktop/Code/orb/backend/app_backend/controller/page_route.py", line 30, in register
    db.session.commit()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/loa/Desktop/Code/orb/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (username, email, password_hash) VALUES (...
                    ^

[SQL: INSERT INTO "user" (username, email, password_hash) VALUES (%(username)s, %(email)s, %(password_hash)s) RETURNING "user".id]
[parameters: {'username': 'kdy', 'email': 'kdy@gmail.com', 'password_hash': 'scrypt:32768:8:1$qcmT29nrCSvHrO3O$03f0fa7b026f1e84533057e98e809028bc88c7cb1a7d2dd01198e2c7feb785f78de13c8cfb236d7a7a494d810f1eea82632d037ddf66cb8435e7ca6d6481ae63'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
127.0.0.1 - - [16/Jun/2024 16:52:31] "POST /register HTTP/1.1" 500 -
```

**Comment by kimmason** [comment]
@riverallzero 혹시 flask db upgrade 실행하신 후 진행해도 동일한 문제 발생하시나요? 만약 그래도 해결 안되시면 동옥님께 추가 리뷰 부탁 드려야 할 것 같습니다.

**Comment by riverallzero** [comment]
@kimmason , 해결 되었습니다. 감사합니다.
